<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>File Uploader - Бочаров М. dashboard</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/bootstrap.css">

    <link rel="stylesheet" href="assets/vendors/toastify/toastify.css">
    <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
    <link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">

    <link rel="stylesheet" href="assets/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="assets/vendors/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="assets/css/app.css">
    <link rel="shortcut icon" href="assets/images/favicon.svg" type="image/x-icon">
</head>

<body>
<div id="app">
    <div id="sidebar" class="active">
        <div class="sidebar-wrapper active">
            <div class="sidebar-header">
                <div class="d-flex justify-content-between">
                    <div class="logo">
                        <a href="/login"><img src="#" alt="Logo" srcset=""></a>
                    </div>
                    <div class="toggler">
                        <a href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                    </div>
                </div>
            </div>
            <div class="sidebar-menu">
                <ul class="menu">
                    <li class="sidebar-title">Меню</li>

                    <li
                            class="sidebar-item active ">
                        <a href="/admin" class='sidebar-link'>
                            <i class="bi bi-grid-fill"></i>
                            <span>Загрузка прокси, вк ботов</span>
                        </a>
                    </li>

                    <li
                            class="sidebar-item  ">
                        <a href="/users" class='sidebar-link'>
                            <i class="bi bi-stack"></i>
                            <span>Пользователи</span>
                        </a>
                    </li>

                    <li
                            class="sidebar-item  ">
                        <a href="/tasks" class='sidebar-link'>
                            <i class="bi bi-collection-fill"></i>
                            <span>Задачи на выполнение</span>
                        </a>
                    </li>

                    <li
                            class="sidebar-item  ">
                        <a href="/config" class='sidebar-link'>
                            <i class="bi bi-grid-1x2-fill"></i>
                            <span>Настройки сервера (open API VK)</span>
                        </a>
                    </li>

                    <li
                            class="sidebar-item  ">
                        <a href="form-element-textarea.html" class='sidebar-link'>
                            <i class="bi bi-hexagon-fill"></i>
                            <span></span>
                        </a>
                    </li>

                    <li
                            class="sidebar-item  ">
                        <a href="form-layout.html" class='sidebar-link'>
                            <i class="bi bi-file-earmark-medical-fill"></i>
                            <span></span>
                        </a>
                    </li>

                    <li
                            class="sidebar-item  ">
                        <a href="#" class='sidebar-link'>
                            <i class="bi bi-pen-fill"></i>
                            <span></span>
                        </a>
                    </li>

                    <li
                            class="sidebar-item  ">
                        <a href="table.html" class='sidebar-link'>
                            <i class="bi bi-grid-1x2-fill"></i>
                            <span></span>
                        </a>
                    </li>

                </ul>
            </div>
            <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
        </div>
    </div>
    <div id="main">
        <header class="mb-3">
            <a href="#" class="burger-btn d-block d-xl-none">
                <i class="bi bi-justify fs-3"></i>
            </a>
        </header>

        <div class="page-heading">
            <div class="page-title">
                <div class="row">
                    <div class="col-12 col-md-6 order-md-1 order-last">
                        <h3>Загрузка ботов, прокси серверов и их валидация</h3>
<!--                        <p class="text-subtitle text-muted">File uploader that makes user easier to upload their files</p>-->
                    </div>
                    <div class="col-12 col-md-6 order-md-2 order-first">
                        <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/admin">Админ-панель</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Загрузка прокси / ботов вк</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <section class="section">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title">Загрузка прокси / валидация</h5>
                            </div>
                            <div class="card-content">
                                <div class="card-body">
                                    <form action="/admin/proxy" method="post" enctype="multipart/form-data">
                                        <p class="card-text">Нажмите или перетащите текстовый файл в область чтобы валидировать и загрузить файл
                                        </p>
                                        <label for="formFile" class="form-label">Выберите файл с прокси серверами сервер:порт</label>
                                        <input class="form-control" type="file" id="formFile" name="proxyfile" accept="text/plain">
                                        <button type="submit" class="btn btn-primary me-1 mb-1">Загрузить</button>
                                        <p class="card-text"></p>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title">Загрузка ботов ВК / валидация</h5>
                            </div>
                            <div class="card-content">
                                <div class="card-body">
                                    <form action="/admin/bots" method="post" enctype="multipart/form-data">
                                        <p class="card-text">Нажмите чтобы валидировать файл с ботами ВК и загрузить файл в базу
                                        </p>
                                            <label for="formFile1" class="form-label">Выберите текстовый файл с ботами вк логин:пароль</label>
                                            <input class="form-control" type="file" id="formFile1" name="botsfile" accept="text/plain">
                                            <button type="submit" class="btn btn-primary me-1 mb-1">Загрузить</button>
                                        <p class="card-text"></p>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title">Информация о прокси в базе данных</h5>
                            </div>
                            <div class="card-content">
                                <div class="card-body">
                                    <p class="card-text">
                                        В базе находится  прокси серверов:
                                    </p>
                                    <p class="card-text">
                                        Рабочие: 
                                    </p>
                                    <p class="card-text">
                                        из них socks5 типа: 
                                    </p>
                                    <p class="card-text">
                                        из них socks4 типа: 
                                    </p>
                                    <p class="card-text">
                                        из них https типа: 
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title">Информация о ботах ВК в базе данных</h5>
                            </div>
                            <div class="card-content">
                                <div class="card-body">
                                    <p class="card-text">
                                        В базе находится  ВК аккаунтов-ботов:
                                    </p>
                                    <p class="card-text">
                                        Рабочие (доступна авторизация): 
                                    </p>
                                    <p class="card-text">
                                        Из них женского пола: 
                                    </p>
                                    <p class="card-text">
                                        Из них мужского пола: 
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>

        <footer>
            <div class="footer clearfix mb-0 text-muted">
                <div class="float-start">
                    <p>2022 Название сервиса</p>
                </div>
                <div class="float-end">
                    <p>Создано <span class="text-danger"><i class="bi bi-heart-fill icon-mid"></i></span>
                        <a href="#">Чтото еще</a></p>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="assets/js/bootstrap.bundle.min.js"></script>
<script src="assets/js/mazer.js"></script>
<script src="assets/vendors/toastify/toastify.js"></script>
<script src="assets/js/jquery.js"></script>
<script></script>
<script>
</script>
</body>

</html>

