<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Восстановление пароля - Бочаров М. dashboard</title>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/bootstrap.css">
    <link rel="stylesheet" href="assets/vendors/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="assets/css/app.css">
    <link rel="stylesheet" href="assets/css/pages/auth.css">
</head>

<body>
    <div id="auth">
        
<div class="row h-100">
    <div class="col-lg-5 col-12">
        <div id="auth-left">
            <div class="auth-logo">
                <p class="auth-title" id="logo">НАЗВАНИЕ</p>
<!--                <a href="/login"><img src="#" alt="Logo"></a>-->
            </div>
            <h1 class="auth-title">Забыли пароль?</h1>
            
            <p class="auth-subtitle mb-5">Введите свою почту и мы вышлем вам данные для входа</p>
            


            <form action="/forgotpassword" method="post">
                <div class="form-group position-relative has-icon-left mb-4">
                    <input name="email" type="email" class="form-control form-control-xl" placeholder="Email">
                    <div class="form-control-icon">
                        <i class="bi bi-envelope"></i>
                    </div>
                </div>
                <button class="btn btn-primary btn-block btn-lg shadow-lg mt-5">Отправить</button>
            </form>
            <div class="text-center mt-5 text-lg fs-4">
                <p class='text-gray-600'>Знаешь свои данные? <a href="/login" class="font-bold">Войти</a>.
                </p>
            </div>
            <footer>

                <div class="footer clearfix mb-0 text-muted">
                    <div class="float-start" style="width:100%;">
                        <p style="text-align: center; margin:0; padding: 0;"> <span class="">КОМАНПИЯ</span></p>
                        <p style="text-align: center">2020</p>
                    </div>
                    <div class="float-end" style="width:100%;">
                        <p style="text-align: center; margin:0; padding: 0;"> <span class="">Контакты</span></p>
                        <ul style="list-style-type: none; list-style: none; text-align: center;">
                            <li>
                                <a href="www.alphsens.com"></a>
                            </li>
                            <li>
                                <a href="mailto:info@alphasens.com"></a>
                            </li>
                        </ul>

                    </div>
                </div>
            </footer>
        </div>
    </div>
    <div class="col-lg-7 d-none d-lg-block">
        <div id="auth-right">

        </div>
    </div>
</div>

    </div>
<script src="assets/js/validate.js"></script>
</body>

</html>
