<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вход в личный кабинет пользователя</title>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/bootstrap.css">
    <link rel="stylesheet" href="assets/vendors/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="assets/css/app.css">
    <link rel="stylesheet" href="assets/css/pages/auth.css">
</head>

<body>
    <div id="auth">
        
<div class="row h-100">
    <div class="col-lg-5 col-12">
        <div id="auth-left">
            <div class="auth-logo">
                <p class="auth-title" id="logo">НАЗВАНИЕ</p>
<!--                <a href="/login"></a>-->
            </div>
            <h1 class="auth-title">Вход на сайт</h1>
            <p class="auth-subtitle">Введите данные для входа, номер телефона и пароль, полученный по смс</p>
            
            
            <form action="/login/auth" method="post">
                
                <div class="form-group position-relative has-icon-left mb-4">
                    
                    <input type="text" name="tel" id="tel" class="form-control form-control-xl"
                           placeholder="Номер телефона" required>
                    
                    <div class="form-control-icon">
                        <i class="bi bi-person"></i>
                    </div>
                </div>
                <button type="button" class="btn btn-primary btn-block btn-lg shadow-lg info">Отправить СМС для входа</button>
                <div class="form-group position-relative has-icon-left mb-4 mt-4">
                    
                    <input type="password" name="password" id="password" class="form-control form-control-xl" placeholder="Пароль" required>
                    
                    <div class="form-control-icon">
                        <i class="bi bi-shield-lock"></i>
                    </div>
                </div>
                <div class="form-check form-check-lg d-flex align-items-end">
                    <input class="form-check-input me-2" name="savelogin" type="checkbox" value="true" id="flexCheckDefault">
                    <label class="form-check-label text-gray-600" for="flexCheckDefault">
                        Запомнить данные для входа
                    </label>
                </div>
                
                <button type="submit" class="btn btn-primary btn-block btn-lg shadow-lg">Войти</button>
            </form>
<!--            <div class="text-center text-lg mt-4 fs-4">-->
<!--                <p class="text-gray-600">-->
<!--                    войти через свой аккаунт-->
<!--                </p>-->
<!--            </div>-->
            <div class="text-center text-lg fs-4">
<!--                <p class="text-gray-600 accounts">-->
<!--                    <a id="vkbutton" href="/auth/vkontakte" class="font-bold"></a>-->
<!--                    <a id="facebookbutton" href="#" class="font-bold"></a>-->
<!--                    <a id="instagrambutton" href="#" class="font-bold"></a>-->
<!--                    <a id="goooglebutton" href="#" class="font-bold"></a>-->
<!--                    <a id="youtubebutton" href="#" class="font-bold"></a>-->
<!--                </p>-->

                <p class="text-gray-600">Заполняя форму, Вы даете
                    согласие на обработку персональных данных и принимаете условия  <a href="/privacy.phtml" class="font-bold">пользовательского соглашения</a>.</p>
                <p class="text-gray-600">Нет аккаунта? <a href="/register" class="font-bold">Регистрация</a>.</p>
            </div>
            <footer>

                <div class="footer clearfix mb-0 text-muted">
                    <div class="float-start" style="width:100%">
                        <p style="text-align: center; margin:0; padding: 0;"> <span class="">© ООО «Парус» 2022</span></p>
                        <p style="text-align: center"></p>
                    </div>
                    <div class="float-end" style="width:100%">
                        <p style="text-align: center; margin:0; padding: 0;"> <span class="">Контакты</span></p>
                        <ul style="list-style-type: none; list-style: none; text-align: center;">
                            <li>
                                <a href="#"> </a>
                            </li>
                            <li>
                                <a href="mailto:info@"> </a>
                            </li>
                        </ul>

                    </div>
                </div>
            </footer>
        </div>
    </div>
    <div class="col-lg-7 d-none d-lg-block">
        <div id="auth-right">

        </div>
    </div>
</div>

    </div>

<script src="assets/js/validate.js"></script>
<script src="assets/js/jquery.js"></script>
<script src="assets/vendors/toastify/toastify.js"></script>
<script>
</script>
</body>

</html>
