<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=$this->title;?></title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/bootstrap.css">

    <link rel="stylesheet" href="assets/vendors/toastify/toastify.css">
    <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
    <link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">

    <link rel="stylesheet" href="assets/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="assets/vendors/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="assets/css/app.css">
    <link rel="shortcut icon" href="assets/images/favicon.svg" type="image/x-icon">
</head>

<body>
<div id="app">
    <div id="sidebar" class="active">
        <div class="sidebar-wrapper active">
            <div class="sidebar-header">
                <div class="d-flex justify-content-between">
                    <div class="logo">
                        <a href="/login"><img src="#" alt="ООО Парус" srcset=""></a>
                    </div>
                    <div class="toggler">
                        <a href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                    </div>
                </div>
            </div>
            <div class="sidebar-menu">
                <ul class="menu">
                    <li class="sidebar-title">Меню</li>

                    <li
                            class="sidebar-item active ">
                        <a href="/cabinet" class='sidebar-link'>
                            <i class="bi bi-grid-fill"></i>
                            <span>Информационный блок</span>
                        </a>
                    </li>

                    <li
                            class="sidebar-item  ">
                        <a href="/cabinetnotify" class='sidebar-link'>
                            <i class="bi bi-stack"></i>
                            <span>Настройка уведомлений</span>
                        </a>
                    </li>

                </ul>
            </div>
            <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
        </div>
    </div>
    <div id="main">
        <header class="mb-3">
            <a href="#" class="burger-btn d-block d-xl-none">
                <i class="bi bi-justify fs-3"></i>
            </a>
        </header>

        <div class="page-heading">
            <div class="page-title">
                <div class="row">
                    <div class="col-12 col-md-6 order-md-1 order-last">
                        <h3>Личный кабинет</h3>
                    </div>
                    <div class="col-12 col-md-6 order-md-2 order-first">
                        <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active" aria-current="page">Личный кабинет</li>
                                <li class="breadcrumb-item"><a href="/login">Выйти</a></li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <section class="section">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title">Информационный блок о клиенте</h5>
                            </div>
                            <div class="card-content">
                                <div class="card-body" style="padding:0;">
                                    <div class="list-group">
                                        <span class="list-group-item">
                                            <b>Общие данные</b>
                                        </span>
                                        <span class="list-group-item"><b>Номер телефона пользователя:</b> 7(999)777-77-77</span>
                                        <span class="list-group-item disabled"><b>Электронная почта:</b> name@mail.mail <button></button></span>
                                        <span class="list-group-item"><b>ФИО пользователя:</b> Иванов Иван Иванович</span>
                                        <span class="list-group-item"><b>Организация:</b> Наименование организации</span>
                                        <!-- Button trigger for basic modal -->
                                        <button type="button" class="btn btn-outline-primary block" data-bs-toggle="modal"
                                                data-bs-target="#default">
                                            Мои данные неверны
                                        </button>

                                        <!--Basic Modal -->
                                        <div class="modal fade text-left" id="default" tabindex="-1" role="dialog"
                                             aria-labelledby="myModalLabel1" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-scrollable" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="myModalLabel1">Мои неверные данные</h5>
                                                        <button type="button" class="close rounded-pill" data-bs-dismiss="modal"
                                                                aria-label="Close">
                                                            <i data-feather="x"></i>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group mb-3">
                                                            <label for="exampleFormControlTextarea1" class="form-label">Введите неверные данные</label>
                                                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn" data-bs-dismiss="modal">
                                                            <i class="bx bx-x d-block d-sm-none"></i>
                                                            <span class="d-none d-sm-block">Закрыть</span>
                                                        </button>
                                                        <button type="button" class="btn btn-primary ml-1" data-bs-dismiss="modal">
                                                            <i class="bx bx-check d-block d-sm-none"></i>
                                                            <span class="d-none d-sm-block">Отправить администратору</span>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                    </div>

<!--                                    <form action="/admin/proxy" method="post" enctype="multipart/form-data">-->
<!--                                        <p class="card-text">Нажмите или перетащите текстовый файл в область чтобы валидировать и загрузить файл-->
<!--                                        </p>-->
<!--                                        <label for="formFile" class="form-label">Выберите файл с прокси серверами сервер:порт</label>-->
<!--                                        <input class="form-control" type="file" id="formFile" name="proxyfile" accept="text/plain">-->
<!--                                        <button type="submit" class="btn btn-primary me-1 mb-1">Загрузить</button>-->
<!--                                        <p class="card-text"></p>-->
<!--                                    </form>-->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title">Информация о сданных тестах</h5>
                            </div>
                            <div class="card-content">
                                <div class="card-body" style="padding:0;">
                                    <table class="table table-striped mb-0">
                                        <thead>
                                        <tr>
                                            <th>Дата теста</th>
                                            <th>Адрес по которому сдан тест</th>
                                            <th>Результат</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td class="text-bold-500">Дата</td>
                                            <td>Адрес</td>
                                            <td class="text-bold-500">
                                                <button type="button" class="btn btn-success">
                                                    Положительный <span class="badge bg-transparent">+</span>
                                                </button>
                                            </td>
                                            <td><a href="#"><i
                                                            class="badge-circle badge-circle-light-secondary font-medium-1"
                                                            data-feather="mail"></i></a></td>
                                        </tr>
                                        </tbody>

                                    </table>
                                    <b>Тест действителен еще 10 дней</b>
                                    <div class="card-text mt-10">
                                        <button type="submit" id="sendspr" class="btn btn-primary btn-block btn-lg shadow-lg mt-2">Заказать справку на email</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </section>
        </div>

        <footer>
            <div class="footer clearfix mb-0 mt-10 text-muted">
                <div class="float-start">
                    <p>2022 ООО "Парус"</p>
                </div>
                <div class="float-end">
                    <p>Чтото еще  <span class="text-danger"></span>
                        <a href="#">Чтото еще</a></p>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="assets/js/bootstrap.bundle.min.js"></script>
<script src="assets/js/mazer.js"></script>
<script src="assets/vendors/toastify/toastify.js"></script>
<script src="assets/js/jquery.js"></script>
<script></script>
<script>
</script>
</body>

</html>

